stages:
- name: Compile
  steps:
  - runScriptConfig:
      image: node:latest
      shellScript: echo aa
- name: Create container
  steps: 
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: myaspnetapp:v1
      pushRemote: false
      registry: 127.0.0.1:34501
    env: 
      PLUGIN_DEBUG: "true" 
- name: Deploy container workload
  steps:
   - applyYamlConfig:
        path: ./deployment.yaml
timeout: 60