apiVersion: apps/v1beta2
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    field.cattle.io/creatorId: user-wv5rw
    field.cattle.io/publicEndpoints: '[{"addresses":["10.19.199.7"],"port":31084,"protocol":"TCP","serviceName":"default:myaspnet-nodeport","allNodes":true}]'
  creationTimestamp: 2019-01-30T15:08:37Z
  generation: 2
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: deployment-default-myaspnet
  name: myaspnet
  namespace: default
  resourceVersion: "1017154"
  selfLink: /apis/apps/v1beta2/namespaces/default/deployments/myaspnet
  uid: eb8608ea-24a0-11e9-8e87-005056bf847d
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-default-myaspnet
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: 2019-01-30T15:08:36Z
        field.cattle.io/ports: '[[{"containerPort":8080,"dnsName":"myaspnet-nodeport","kind":"NodePort","name":"8080tcp01","protocol":"TCP","sourcePort":0}]]'
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-default-myaspnet
    spec:
      containers:
      - image: docker-registry.p-fp567-pipeline/myaspnetapp:v1
        imagePullPolicy: Always
        name: myaspnet
        ports:
        - containerPort: 8080
          name: 8080tcp01
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

